### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by ynnckcmprnl** [PhotoPay/photopay-ios#4]
Would it be possible to add Cocoapods (and/or Carthage/SPM) support, so we don't have to include the framework in the repository.
Like https://github.com/microblink/blinkid-ios.

**Comment by somyaguptagit** [comment]
Hello Yannick,

You can contact our sales team at sales@microblink.com to get an account on developer hub as PhotoPay is distributed from there.

**Comment by ynnckcmprnl** [comment]
We have Photopay up & running in our app for a while, version 7.13.0. 

We were hoping there was an alternative other than manually copying the xcframework in our codebase and committing it. Reason being the xcframework contains at least 1 file larger than 100MB, which is the file size limit on GitHub without resorting to Git LFS.

Right now all our dependencies (paid & open source) are pulled in using Carthage or Cocoapods, with 1 exception: Photopay. We would rather not have to commit the xcframework in the repository and pull it in using Carthage or Cocoapods. Especially since we would have to start using Git LFS to get around the file size issue.

**Comment by somyaguptagit** [comment]
Hello Yannick,

Unfortunately the only way to get the framework is by manually copying the xcframework in codebase. However, PhotoPay version 8 is much smaller in size since it only contains the recognizers & parsers for pay-slip scanning and you can download it from Developer Hub and let us know if the size exceeds more then 100MB.
Would you be able to share with us which recognizers you are using with PhotoPay?
